#!/usr/bin/env python3
"""Generate docs/40-spec/INDEX/ (P5): requirements, entities, interfaces, terms,
NFRs and verdict traceability, extracted from the spec chapters.
Usage: python3 docs/tools/build_index.py   (overwrites docs/40-spec/INDEX/)"""
import re, glob, os, collections
ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
SPEC = os.path.join(ROOT, '40-spec')
OUT = os.path.join(SPEC, 'INDEX')
def rel(f): return os.path.relpath(f, SPEC).replace(os.sep, '/')
chapters = []           # (spec id, title, path)
reqs, apis, ents, terms, nfrs = [], [], [], [], []
vrd_use = collections.defaultdict(set)
spec_files = sorted(f for f in glob.glob(os.path.join(SPEC, '**/*.md'), recursive=True) if '/INDEX/' not in f)
for f in spec_files:
    s = open(f, encoding='utf-8').read()
    m = re.search(r'^id: (\S+)', s, re.M); t = re.search(r'^title: "?(.*?)"?$', s, re.M)
    sid = m.group(1) if m else '?'
    chap = re.sub(r'^(SPEC-\d+)-\d+$', r'\1', sid)
    if re.fullmatch(r'SPEC-\d+|ADR-\d+', sid): chapters.append((sid, t.group(1) if t else '', rel(f)))
    lines = s.splitlines()
    for n, line in enumerate(lines):
        mm = re.match(r'^#{2,3} (REQ-[A-Z]+-\d{3}) — (.*)', line) or re.match(r'^- (REQ-[A-Z]+-\d{3}): (.*)', line)
        if mm:
            pr = ''
            for k in range(n + 1, min(n + 200, len(lines))):
                pm = re.search(r'\*\*Priority:\*\* (P\d[^\n]*)', lines[k])
                if pm: pr = pm.group(1); break
                if re.match(r'^#{2,3} ', lines[k]): break
            title = mm.group(2).strip()
            if len(title) > 90: title = title[:87] + '…'
            reqs.append((mm.group(1), title.replace('|', '\\|'), pr or ('P0' if mm.group(1).startswith('REQ-CONV') else ''), chap, rel(f)))
        mm = re.match(r'^#{2,3} (API-[A-Z]+-\d{3}) — (.*)', line)
        if mm: apis.append((mm.group(1), mm.group(2).replace('|', '\\|'), chap, rel(f)))
        mm = re.match(r'^(ENT-[A-Za-z0-9]+):\s*$', line)
        if mm:
            purpose = ''
            for k in range(n + 1, min(n + 4, len(lines))):
                pm = re.match(r'\s+purpose: (.*)', lines[k])
                if pm: purpose = pm.group(1).strip().strip('"'); break
            if len(purpose) > 100: purpose = purpose[:97] + '…'
            ents.append((mm.group(1), purpose.replace('|', '\\|'), chap, rel(f)))
        mm = re.match(r'^### (TERM-[A-Za-z0-9]+)\s*$', line)
        if mm and 'Name>' not in line:
            d = lines[n + 1] if n + 1 < len(lines) else ''
            d = re.sub(r'^- \*\*Definition:\*\* ', '', d)
            if len(d) > 110: d = d[:107] + '…'
            terms.append((mm.group(1), d.replace('|', '\\|'), rel(f)))
        mm = re.match(r'^\| (NFR-[A-Z]+-\d{3}) \| ([^|]*) \| ([^|]*) \|', line)
        if mm and ('32-nfr-catalogue' not in f or '-9' in mm.group(1)[-4:-2]):
            nfrs.append((mm.group(1), mm.group(2).strip(), mm.group(3).strip(), chap))
    for v in set(re.findall(r'\bVRD-\d{2}-\d{2}\b', s)): vrd_use[v].add(chap)
cmp_titles = {}
for f in sorted(glob.glob(os.path.join(ROOT, '30-comparison', '*.md'))):
    for mm in re.finditer(r'^### (VRD-\d{2}-\d{2}) — (.*)', open(f, encoding='utf-8').read(), re.M):
        cmp_titles[mm.group(1)] = mm.group(2).replace('|', '\\|')
os.makedirs(OUT, exist_ok=True)
def fm(i, title, extra=''):
    return f'---\nid: {i}\ntitle: "{title}"\nstatus: complete\nphase: P5\ndepends_on: [SPEC-00]\nsources: []\n---\n\n# {title}\n\nGenerated by `docs/tools/build_index.py` from the chapters. Do not edit by hand.{extra}\n'
def key(i):
    p = i.split('-'); return (p[0], p[1], int(p[2]) if p[2].isdigit() else 0)
mods = collections.defaultdict(list)
for r in sorted(reqs, key=lambda r: key(r[0])): mods[r[0].split('-')[1]].append(r)
prio = collections.Counter(r[2][:2] for r in reqs)
# 00-index
o = fm('SPEC-INDEX', 'Specification Index')
o += '\n## Files\n\n| File | Content |\n|---|---|\n| `00-index.md` | chapters, ADRs, counts |\n| `01-requirements.md` | all REQ items by module |\n| `02-entities-interfaces.md` | all ENT and API items |\n| `03-terms-nfr.md` | glossary terms and NFRs |\n| `04-traceability.md` | verdict → chapter traceability |\n'
o += f'\n## Counts\n\n| Item | Count |\n|---|---|\n| Chapters (SPEC) | {sum(1 for c in chapters if c[0].startswith("SPEC"))} |\n| ADRs | {sum(1 for c in chapters if c[0].startswith("ADR"))} |\n| Requirements (REQ) | {len(reqs)} (P0 {prio["P0"]}, P1 {prio["P1"]}, P2 {prio["P2"]}) |\n| Entities (ENT) | {len(ents)} |\n| Interfaces (API) | {len(apis)} |\n| Terms (TERM) | {len(terms)} |\n| Non-functional (NFR) | {len(nfrs)} |\n| Verdicts traced | {len(cmp_titles)} |\n'
o += '\n## Chapters and ADRs\n\n| ID | Title | File |\n|---|---|---|\n' + ''.join(f'| {i} | {t} | `{p}` |\n' for i, t, p in sorted(chapters, key=lambda c: (c[0][:3], c[0])))
open(os.path.join(OUT, '00-index.md'), 'w').write(o)
# 01 requirements
o = fm('SPEC-INDEX-1', 'Index of Requirements')
for m_, lst in sorted(mods.items()):
    o += f'\n## {m_}\n\n| ID | Title | Priority | File |\n|---|---|---|---|\n' + ''.join(f'| {i} | {t} | {p} | `{fl}` |\n' for i, t, p, c, fl in lst)
open(os.path.join(OUT, '01-requirements.md'), 'w').write(o)
# 02 entities & interfaces
o = fm('SPEC-INDEX-2', 'Index of Entities and Interfaces')
o += '\n## Entities\n\n| ENT | Purpose | Chapter | File |\n|---|---|---|---|\n' + ''.join(f'| {i} | {p} | {c} | `{fl}` |\n' for i, p, c, fl in sorted(ents))
o += '\n## Interfaces\n\n| API | Name | Chapter | File |\n|---|---|---|---|\n' + ''.join(f'| {i} | {n} | {c} | `{fl}` |\n' for i, n, c, fl in sorted(apis, key=lambda a: key(a[0])))
open(os.path.join(OUT, '02-entities-interfaces.md'), 'w').write(o)
# 03 terms & nfr
o = fm('SPEC-INDEX-3', 'Index of Terms and NFRs')
o += '\n## Terms\n\n| TERM | Definition | File |\n|---|---|---|\n' + ''.join(f'| {i} | {d} | `{fl}` |\n' for i, d, fl in sorted(terms))
o += '\n## Non-functional requirements\n\n| NFR | Requirement | Target | Chapter |\n|---|---|---|---|\n' + ''.join(f'| {i} | {r} | {t} | {c} |\n' for i, r, t, c in sorted(set(nfrs), key=lambda n: key(n[0])))
open(os.path.join(OUT, '03-terms-nfr.md'), 'w').write(o)
# 04 traceability
o = fm('SPEC-INDEX-4', 'Verdict Traceability', '\n\nEvery verdict of P2 (CMP-NN) and the spec chapters/ADRs that consume or defer it (SPEC-00 §6).')
o += '\n| Verdict | Title | Consumed in |\n|---|---|---|\n' + ''.join(f'| {v} | {cmp_titles[v]} | {", ".join(sorted(vrd_use.get(v, []))) or "**NOT CONSUMED**"} |\n' for v in sorted(cmp_titles))
open(os.path.join(OUT, '04-traceability.md'), 'w').write(o)
print(len(reqs), len(ents), len(apis), len(terms), len(set(nfrs)), len(cmp_titles), 'unconsumed:', [v for v in cmp_titles if not vrd_use.get(v)])
