#!/usr/bin/env python3
"""Check docs/finance-requirements and generate its traceability file.

Checks:
  * every file has front matter with id, title and status;
  * every ID (FIN-*, ROLE-*) is defined exactly once and every reference resolves;
  * every requirement block has Requirement, Priority (Must/Should/Could), Basis and a
    numbered Acceptance list;
  * every scenario has Steps, Expected and Covers, and covers only defined requirements;
  * every Must requirement is covered by at least one scenario (Should/Could gaps are listed).
Writes 90-traceability.md (requirement -> scenarios).

Usage: python3 docs/tools/check_finance.py
"""
import os
import re
import sys
import collections

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'finance-requirements')
OUT = os.path.join(ROOT, '90-traceability.md')
ID = r'(?:FIN-[A-Z]{2,3}-\d{2,3}|ROLE-[A-Z][A-Za-z]+|FIN-README)'
REF = re.compile(r'(?<![A-Za-z0-9-])(' + ID + r')(?![A-Za-z0-9])')
REQ = re.compile(r'^### (FIN-(?!SCN)[A-Z]{2}-\d{3}) — (.+?)\n(.*?)(?=^#{1,3} |\Z)', re.M | re.S)
SCN = re.compile(r'^### (FIN-SCN-\d{2}) — (.+?)\n(.*?)(?=^#{1,3} |\Z)', re.M | re.S)


def main():
    errors, texts = [], {}
    for f in sorted(os.listdir(ROOT)):
        if f.endswith('.md') and f != '90-traceability.md':
            texts[f] = open(os.path.join(ROOT, f), encoding='utf-8').read()
    defs = collections.defaultdict(list)
    for f, s in texts.items():
        fm = re.match(r'^---\n(.*?)\n---\n', s, re.S)
        meta = dict(re.findall(r'^(\w+): *(.*)$', fm.group(1), re.M)) if fm else {}
        for k in ('id', 'title', 'status'):
            if k not in meta:
                errors.append('%s: front matter lacks %s' % (f, k))
        if meta.get('id'):
            defs[meta['id']].append(f)
        body = re.sub(r'^```.*?^```', '', s, flags=re.S | re.M)
        for m in re.finditer(r'^#{3,4} (' + ID + r') — ', body, re.M):
            defs[m.group(1)].append(f)
        for m in re.finditer(r'^\| (' + ID + r') \|', body, re.M):
            defs[m.group(1)].append(f)
        for m in re.finditer(r'^## .*\((FIN-EXP-\d{2})\)$', body, re.M):
            defs[m.group(1)].append(f)
    for i, fs in defs.items():
        if len(fs) > 1:
            errors.append('duplicate definition %s in %s' % (i, fs))
    for f, s in texts.items():
        body = re.sub(r'^```.*?^```', '', s, flags=re.S | re.M)
        for m in REF.finditer(body):
            if m.group(1) not in defs:
                errors.append('%s: undefined %s' % (f, m.group(1)))

    reqs = collections.OrderedDict()
    for f, s in texts.items():
        for m in REQ.finditer(s):
            rid, title, blk = m.groups()
            for fld in ('Requirement', 'Priority', 'Basis', 'Acceptance'):
                if '- **%s:**' % fld not in blk:
                    errors.append('%s: %s lacks %s' % (f, rid, fld))
            pr = re.search(r'\*\*Priority:\*\* (\w+)', blk)
            if not pr or pr.group(1) not in ('Must', 'Should', 'Could'):
                errors.append('%s: %s has an invalid priority' % (f, rid))
            if not re.search(r'\*\*Acceptance:\*\*\n\s+1\. ', blk):
                errors.append('%s: %s acceptance is not a numbered list' % (f, rid))
            reqs[rid] = (title.strip(), pr.group(1) if pr else '?', f)

    covered = collections.defaultdict(list)
    scns = collections.OrderedDict()
    for f, s in texts.items():
        for m in SCN.finditer(s):
            sid, title, blk = m.groups()
            for fld in ('Steps', 'Expected', 'Covers'):
                if '- **%s:**' % fld not in blk:
                    errors.append('%s: %s lacks %s' % (f, sid, fld))
            cov = re.search(r'\*\*Covers:\*\* (.+)', blk)
            for r in re.findall(ID, cov.group(1) if cov else ''):
                if r not in reqs:
                    errors.append('%s: %s covers unknown requirement %s' % (f, sid, r))
                covered[r].append(sid)
            scns[sid] = title.strip()

    gaps = [r for r, v in reqs.items() if not covered.get(r)]
    must_gaps = [r for r in gaps if reqs[r][1] == 'Must']
    for r in must_gaps:
        errors.append('Must requirement %s is not covered by any scenario' % r)

    counts = collections.Counter(v[1] for v in reqs.values())
    lines = ['---', 'id: FIN-DOC-90', 'title: Traceability', 'status: draft', '---', '', '# Traceability', '',
             '> Generated by `docs/tools/check_finance.py`. Do not edit by hand.', '',
             '| Priority | Requirements | Covered by a scenario |', '|---|---|---|']
    for p in ('Must', 'Should', 'Could'):
        lines.append('| %s | %d | %d |' % (p, counts[p], sum(1 for r, v in reqs.items() if v[1] == p and covered.get(r))))
    lines += ['', '## Requirement to scenario', '', '| Requirement | Title | Priority | Scenarios |', '|---|---|---|---|']
    for r, (t, p, f) in reqs.items():
        lines.append('| %s | %s | %s | %s |' % (r, t, p, ', '.join(sorted(set(covered.get(r, [])))) or '—'))
    if gaps:
        lines += ['', '## Not covered by a scenario', '',
                  'Should and Could requirements below are accepted by their own acceptance criteria during the',
                  'acceptance run, outside the scenarios.', '']
        lines += ['- %s (%s)' % (r, reqs[r][1]) for r in gaps]
    with open(OUT, 'w', encoding='utf-8') as fh:
        fh.write('\n'.join(lines) + '\n')

    print('finance: files %d, requirements %d (%s), scenarios %d, uncovered %d (Must %d)' % (
        len(texts), len(reqs), ', '.join('%s %d' % (k, counts[k]) for k in ('Must', 'Should', 'Could')),
        len(scns), len(gaps), len(must_gaps)))
    for e in errors:
        print('ERROR', e)
    print('errors: %d' % len(errors))
    return 1 if errors else 0


if __name__ == '__main__':
    sys.exit(main())
