#!/usr/bin/env python3
"""Generate the indexes in docs/50-system/INDEX/ (never edit them by hand).

  00-index.md          list of indexes
  01-documents.md      every document: id, title, status, phase, path
  02-ids-<group>.md    every defined ID with its title and defining file, grouped by kind
  03-statistics.md     counts by kind, by phase and by system
  04-system-phase.md   design items (DSN) by system and phase

Usage: python3 docs/tools/gen_indexes.py
"""
import os
import re
import collections

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '50-system')
OUT = os.path.join(ROOT, 'INDEX')

HEAD = re.compile(r'^#{3,4} ([A-Z]+-[A-Za-z0-9-]+?) — (.+)$', re.M)
ROW = re.compile(r'^\| ((?:PER|CAP|GL|AR|CTR|ENV|EXIT|MET|RSK|SUITE|CST|ASM|OQ|IMP|IN)-[A-Za-z0-9-]+) \| ([^|]+)\|', re.M)
YAML_DAT = re.compile(r'^(DAT-[A-Z][A-Za-z0-9]+):', re.M)
GROUPS = collections.OrderedDict([
    ('requirements', ('FR', 'NR', 'CR', 'SCN', 'CAP', 'PER', 'CST', 'ASM', 'GL')),
    ('standard', ('STD', 'DAT')),
    ('architecture', ('AR', 'CTR', 'DEC')),
    ('design', ('DSN', 'IF')),
    ('phases-verification', ('EXIT', 'MET', 'RSK', 'SUITE', 'VER', 'ENV')),
    ('inputs', ('IN', 'IMP', 'OQ')),
])


def docs():
    for d, _, fs in os.walk(ROOT):
        if os.path.relpath(d, ROOT).startswith('INDEX'):
            continue
        for f in sorted(fs):
            if f.endswith('.md'):
                p = os.path.join(d, f)
                yield os.path.relpath(p, ROOT), open(p, encoding='utf-8').read()


def main():
    os.makedirs(OUT, exist_ok=True)
    documents, ids = [], {}
    dsn_matrix = collections.Counter()
    phase_counts = collections.Counter()
    for rel, text in docs():
        fm = re.match(r'^---\n(.*?)\n---\n', text, re.S)
        meta = dict(re.findall(r'^(\w+): *(.*)$', fm.group(1), re.M)) if fm else {}
        documents.append((meta.get('id', ''), meta.get('title', ''), meta.get('status', ''), meta.get('phase', ''), rel))
        body = re.sub(r'^```(\w*)\n.*?^```', lambda m: m.group(0) if m.group(1) == 'yaml' else '', text, flags=re.S | re.M)
        if 'writing-rules' in rel or 'templates' in rel:
            continue
        for m in HEAD.finditer(body):
            ids.setdefault(m.group(1), (m.group(2).strip(), rel))
        for m in ROW.finditer(body):
            ids.setdefault(m.group(1), (m.group(2).strip()[:100], rel))
        for m in YAML_DAT.finditer(text):
            ids.setdefault(m.group(1), ('data structure', rel))
        for m in re.finditer(r'^### (DSN-([A-Z]+)-\d{3}) — .+?\n(.*?)(?=^#{1,3} |\Z)', body, re.M | re.S):
            ph = re.search(r'\*\*Phase:\*\* (PH-\d)', m.group(3))
            dsn_matrix[(m.group(2), ph.group(1) if ph else '?')] += 1
        for m in re.finditer(r'^### ((?:FR|NR|CR)-[A-Z0-9]+-\d{3}) — .+?\n(.*?)(?=^#{1,3} |\Z)', body, re.M | re.S):
            ph = re.search(r'\*\*Phase:\*\* (PH-\d)', m.group(2))
            phase_counts[(m.group(1).split('-')[0], ph.group(1) if ph else '?')] += 1

    banner = '> Generated by `docs/tools/gen_indexes.py`. Do not edit by hand.'

    def write(name, doc_id, title, lines):
        with open(os.path.join(OUT, name), 'w', encoding='utf-8') as fh:
            fh.write('\n'.join(['---', 'id: %s' % doc_id, 'title: %s' % title, 'status: draft', 'phase: ALL',
                                'depends_on: [UBS-IDX-00]', '---', '', '# ' + title, '', banner, ''] + lines + ['']))

    lines = ['| ID | Title | Status | Phase | Path |', '|---|---|---|---|---|']
    for d in sorted(documents, key=lambda x: x[4]):
        lines.append('| %s | %s | %s | %s | `%s` |' % d)
    write('01-documents.md', 'UBS-IDX-01', 'Index — Documents', lines)

    def kind(i):
        return i.split('-')[0]

    n = 2
    listing = []
    for group, kinds in GROUPS.items():
        lines = []
        for k in kinds:
            items = sorted(i for i in ids if kind(i) == k)
            if not items:
                continue
            lines += ['## %s (%d)' % (k, len(items)), '', '| ID | Title | Defined in |', '|---|---|---|']
            lines += ['| %s | %s | `%s` |' % (i, ids[i][0].replace('|', '/'), ids[i][1]) for i in items]
            lines.append('')
        name = '02-ids-%s.md' % group
        write(name, 'UBS-IDX-%02d' % n, 'Index — IDs: %s' % group, lines)
        listing.append((name, group))
        n += 1

    total = collections.Counter(kind(i) for i in ids)
    lines = ['## Items by kind', '', '| Kind | Count |', '|---|---|']
    lines += ['| %s | %d |' % (k, total[k]) for k in sorted(total)]
    lines += ['', '## Requirements by phase', '', '| Kind | PH-0 | PH-1 | PH-2 | PH-3 | PH-4 | PH-5 |', '|---|---|---|---|---|---|---|']
    for k in ('FR', 'NR', 'CR'):
        lines.append('| %s | %s |' % (k, ' | '.join(str(phase_counts[(k, 'PH-%d' % p)]) for p in range(6))))
    lines += ['', '| Documents | %d |' % len(documents)]
    write('03-statistics.md', 'UBS-IDX-%02d' % n, 'Index — Statistics', lines)
    stats_name = '03-statistics.md'
    n += 1

    systems = sorted({s for s, _ in dsn_matrix})
    lines = ['| System | PH-0 | PH-1 | PH-2 | PH-3 | PH-4 | PH-5 | Total |', '|---|---|---|---|---|---|---|---|']
    for s in systems:
        row = [dsn_matrix[(s, 'PH-%d' % p)] for p in range(6)]
        lines.append('| %s | %s | %d |' % (s, ' | '.join(map(str, row)), sum(row)))
    write('04-system-phase.md', 'UBS-IDX-%02d' % n, 'Index — Design Items by System and Phase', lines)

    lines = ['| File | Content |', '|---|---|', '| `01-documents.md` | every document with ID, title, status, phase and path |']
    lines += ['| `%s` | defined IDs: %s |' % (name, group) for name, group in listing]
    lines += ['| `%s` | counts by kind and phase |' % stats_name, '| `04-system-phase.md` | design items by system and phase |']
    write('00-index.md', 'UBS-IDX-00', 'Generated Indexes', lines)
    print('ids', len(ids), 'documents', len(documents))


if __name__ == '__main__':
    main()
