#!/usr/bin/env python3
"""Generate the feature lists of the phase plans (50-phases/PH-N/01-features.md).

The lists are derived from the requirement catalogue, so they never drift from it:
  * FR items grouped by capability (FR-DOM-NNk belongs to CAP-DOM-NN);
  * NR and CR items;
  * scenarios assigned to the phase.
For PH-1, every item is also assigned to gate 1a or 1b by the rule of DEC-014
(domains and capability exceptions for FR; the NR/CR rule stated in UBS-PH-1 §3).

Usage: python3 docs/tools/gen_phase_features.py   (run from the repository root or anywhere)
"""
import os
import re
import collections

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '50-system')
REQ = os.path.join(ROOT, '10-requirements')
OUT = os.path.join(ROOT, '50-phases')

BLOCK = re.compile(r'^### ((?:FR|NR|CR)-[A-Z0-9]+-\d{3}) — (.+?)$', re.M)
SCN = re.compile(r'^### (SCN-\d{3}) — (.+?)$', re.M)
CAP_ROW = re.compile(r'^\| (CAP-[A-Z]+-\d{2}) \| ([^|]+?) \|', re.M)

# DEC-014 gate rule for FR items in PH-1
GATE_1A_DOMAINS = {'MODEL', 'VER', 'TIME', 'LEDG', 'TXN', 'LOGIC', 'PROOF', 'FILE', 'ANL', 'STD', 'DEV'}
GATE_1A_CAP_EXCEPTIONS = {'CAP-IAM-03', 'CAP-IAM-09', 'CAP-TEN-01', 'CAP-TEN-02', 'CAP-OPS-01',
                          'CAP-OPS-02', 'CAP-PKG-07', 'CAP-LOC-03'}
GATE_1B_CAP_EXCEPTIONS = {'CAP-DEV-06'}
# UBS-PH-1 §3 rule for NR and CR items in PH-1
GATE_1A_NR_AREAS = {'DET', 'MAINT', 'PORT', 'COMPAT'}
GATE_1A_NR_ITEMS = {'NR-PERF-001', 'NR-PERF-002', 'NR-PERF-003', 'NR-PERF-004', 'NR-PERF-005',
                    'NR-PERF-006', 'NR-PERF-007', 'NR-PERF-010', 'NR-DUR-001', 'NR-DUR-005',
                    'NR-SEC-002', 'NR-SEC-004'}

PHASE_TITLES = {
    'PH-0': 'Foundations and de-risking',
    'PH-1': 'Kernel and single-node server',
    'PH-2': 'First business package (Basic Finance) and production server',
    'PH-3': 'CPA audit drill, evidence and governed AI',
    'PH-4': 'Devices, platform scale and ecosystem',
    'PH-5': 'Federation and the open network',
}


def field(block, name):
    m = re.search(r'\*\*' + re.escape(name) + r':\*\* ([^·\n]+)', block)
    return m.group(1).strip() if m else ''


def read_all(folder):
    for dirpath, _, files in os.walk(folder):
        for f in sorted(files):
            if f.endswith('.md'):
                with open(os.path.join(dirpath, f), encoding='utf-8') as fh:
                    yield fh.read()


def main():
    items = []       # (id, title, phase, priority)
    scenarios = []   # (id, title, phase)
    caps = {}
    for text in read_all(REQ):
        for m in CAP_ROW.finditer(text):
            caps[m.group(1)] = m.group(2).strip()
        heads = list(BLOCK.finditer(text))
        for i, m in enumerate(heads):
            end = heads[i + 1].start() if i + 1 < len(heads) else len(text)
            block = text[m.start():end]
            items.append((m.group(1), m.group(2).strip(), field(block, 'Phase'), field(block, 'Priority')))
        sheads = list(SCN.finditer(text))
        for i, m in enumerate(sheads):
            end = sheads[i + 1].start() if i + 1 < len(sheads) else len(text)
            blk = text[m.start():end]
            if '**Status:** Deferred' in blk:
                continue
            scenarios.append((m.group(1), m.group(2).strip(), field(blk, 'Phase')))

    def cap_of(fr):
        _, dom, num = fr.split('-')
        return 'CAP-%s-%02d' % (dom, int(num) // 10)

    def gate(item_id):
        kind, area, _ = item_id.split('-')
        if kind == 'FR':
            cap = cap_of(item_id)
            if cap in GATE_1B_CAP_EXCEPTIONS:
                return '1b'
            if area in GATE_1A_DOMAINS or cap in GATE_1A_CAP_EXCEPTIONS:
                return '1a'
            return '1b'
        if kind == 'NR' and (area in GATE_1A_NR_AREAS or item_id in GATE_1A_NR_ITEMS):
            return '1a'
        return '1b'

    for n in range(6):
        ph = 'PH-%d' % n
        mine = [it for it in items if it[2] == ph]
        frs = [it for it in mine if it[0].startswith('FR-')]
        nrs = [it for it in mine if it[0].startswith('NR-')]
        crs = [it for it in mine if it[0].startswith('CR-')]
        scs = [s for s in scenarios if s[2].startswith(ph)]
        gated = ph == 'PH-1'
        lines = ['---', 'id: UBS-PHF-%d' % n,
                 'title: %s — Feature List (generated)' % ph,
                 'status: draft', 'phase: %s' % ph, 'depends_on: [UBS-PH-%d]' % n, '---', '',
                 '# %s — %s: Feature List' % (ph, PHASE_TITLES[ph]), '',
                 '> Generated by `docs/tools/gen_phase_features.py` from the requirement catalogue. '
                 'Do not edit by hand; change the requirement blocks and regenerate.', '',
                 '## Summary', '',
                 '| Kind | Count |', '|---|---|',
                 '| Functional requirements (FR) | %d |' % len(frs),
                 '| Non-functional requirements (NR) | %d |' % len(nrs),
                 '| Compliance requirements (CR) | %d |' % len(crs),
                 '| Scenarios (SCN) | %d |' % len(scs), '']
        if gated:
            cnt = collections.Counter(gate(it[0]) for it in mine)
            lines += ['| Gate | Requirements |', '|---|---|',
                      '| 1a (engine core) | %d |' % cnt['1a'], '| 1b (governance and services) | %d |' % cnt['1b'], '']
        lines += ['## Functional requirements by capability', '']
        by_cap = collections.OrderedDict()
        for it in sorted(frs, key=lambda x: (cap_of(x[0]), x[0])):
            by_cap.setdefault(cap_of(it[0]), []).append(it)
        for cap, its in by_cap.items():
            lines.append('### %s %s' % (cap.replace('CAP-', 'Capability '), '— ' + caps.get(cap, '')))
            lines.append('')
            hdr = '| Title | Requirement | Priority |' + (' Gate |' if gated else '')
            lines += [hdr, '|---|---|---|' + ('---|' if gated else '')]
            for it in its:
                lines.append('| %s | %s | %s |%s' % (it[1], it[0], it[3], (' %s |' % gate(it[0])) if gated else ''))
            lines.append('')
        for title, group in (('Non-functional requirements', nrs), ('Compliance requirements', crs)):
            lines += ['## ' + title, '']
            if not group:
                lines += ['None in this phase.', '']
                continue
            hdr = '| Title | Requirement | Priority |' + (' Gate |' if gated else '')
            lines += [hdr, '|---|---|---|' + ('---|' if gated else '')]
            for it in sorted(group):
                lines.append('| %s | %s | %s |%s' % (it[1], it[0], it[3], (' %s |' % gate(it[0])) if gated else ''))
            lines.append('')
        lines += ['## Scenarios', '']
        if scs:
            lines += ['| Title | Scenario |', '|---|---|']
            for s in sorted(scs):
                lines.append('| %s | %s |' % (s[1], s[0]))
        else:
            lines.append('None in this phase.')
        lines.append('')
        folder = os.path.join(OUT, ph)
        os.makedirs(folder, exist_ok=True)
        with open(os.path.join(folder, '01-features.md'), 'w', encoding='utf-8') as fh:
            fh.write('\n'.join(lines))
        print('%s: FR %d, NR %d, CR %d, SCN %d' % (ph, len(frs), len(nrs), len(crs), len(scs)))


if __name__ == '__main__':
    main()
